apiVersion: 1

datasources:
  - name: Prometheus
    uid: document-parser-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 15s
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: document-parser-tempo

  - name: Tempo
    uid: document-parser-tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToMetrics:
        datasourceUid: document-parser-prometheus
      serviceMap:
        datasourceUid: document-parser-prometheus
